"""add_api_provider_and_coingecko_support

Revision ID: 7fc88ed00fae
Revises: 
Create Date: 2025-12-23 05:53:31.205757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc88ed00fae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coingecko_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('api_provider', sa.String(), nullable=True))
    
    # 기존 사용자들의 api_provider를 'cmc'로 설정
    op.execute("UPDATE users SET api_provider = 'cmc' WHERE api_provider IS NULL")
    
    # api_provider에 기본값 설정 (SQLite는 ALTER COLUMN을 지원하지 않으므로 스키마에서만 처리)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_provider')
    op.drop_column('users', 'coingecko_api_key')
    # ### end Alembic commands ###

